-- E17-DEFINITIONS-PERIODS: canonical field registrations for the PLANNING (trying-to-conceive)
-- period onboarding. Sourced from the final verified legacy state (reference-repos/momna-onboarding-legacy,
-- 20260726102000_planning_schema.sql). Machine field IDs/options preserved verbatim.
-- `multi_choice`/`paired_choice` legacy formats become OBJECT-typed fields (selected options, or
-- per-row choices keyed by row id); `max_select` bounds are not enforced by the registry.
-- `lmp`/`treatment_expected_date` use the new minDaysFromNow/maxDaysFromNow relative bounds
-- (past_or_today + 60-day window; future_or_today + 180-day window) instead of fixed calendar dates.
INSERT INTO momna.canonical_field_definitions(field_id, data_type, domain_owner, sensitivity_class, validation_schema, definition_version)
VALUES
    ('onboarding.planning.stage', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["only_thinking", "preparing_next_months", "actively_trying", "fertility_testing", "preparing_treatment", "in_treatment", "not_sure_how_much_tracking"]}'::jsonb, 1),
    ('onboarding.planning.duration', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["first_cycle", "less_than_3m", "3_6m", "6_12m", "more_than_year", "dont_want_to_count", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.lmp', 'DATE', 'ONBOARDING', 'HER_PRIVATE', '{"maxDaysFromNow": 0, "minDaysFromNow": -60}'::jsonb, 1),
    ('onboarding.planning.regularity', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["fairly_predictable", "timing_changes", "often_irregular", "no_periods_now", "just_starting", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.tracking', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["calendar", "opk", "bbt", "cervical_mucus", "wearable_device", "clinic_schedule", "not_tracking_yet", "dont_want_measurements"]}'::jsonb, 1),
    ('onboarding.planning.care', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["discussed_preconception", "working_with_clinician", "first_appointment_scheduled", "choosing_clinician", "not_sought_yet", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.preg_history', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["no", "ended_in_birth", "miscarriage", "chose_to_end", "ended_medical_reasons", "ectopic_or_molar", "more_than_one", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.history_details', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["c_section", "preterm_birth", "high_bp_preeclampsia", "gestational_diabetes", "heavy_blood_loss", "repeated_loss", "procedure_after_pregnancy", "something_else", "no", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.fertility', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["pcos", "endometriosis", "ovulation_problems", "low_ovarian_reserve", "uterus_tubes_condition", "thyroid_condition", "male_factor", "another_reason", "no", "not_tested_yet", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.treatment', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["ovulation_induction", "iui", "ivf_icsi", "embryo_transfer_prep", "other_treatment", "testing_only", "no", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.treatment_expected_date', 'DATE', 'ONBOARDING', 'HER_PRIVATE', '{"minDaysFromNow": 0, "maxDaysFromNow": 180}'::jsonb, 1),
    ('onboarding.planning.meds', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["folic_acid", "iron", "vitamin_d", "clinician_prescribed", "reviewed_meds", "working_on_sleep", "nutrition_attention", "exercise_regularly", "reducing_alcohol", "nothing_specific_yet", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.conditions', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["chronic_condition", "mental_health_condition", "movement_limits", "food_allergies_restrictions", "recent_surgery_treatment", "clinician_special_instructions", "none", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.family_context', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["testing_complete", "testing_scheduled", "next_step_undecided", "no", "not_discussed_yet", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.family_details', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["condition_in_several_relatives", "congenital_condition", "developmental_condition", "repeated_loss_or_stillbirth", "genetic_counseling_appointment", "something_else", "dont_know_exact_name", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.partner', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["steady_partner", "partner_not_living_together", "on_my_own", "complicated_situation", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.donor_material', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["yes", "no", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.partner_involvement', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["share_equally", "supportive_but_planning_on_me", "tries_hard_to_talk", "not_very_involved", "tension", "pressured_unsafe", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.partner_health', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["completed_evaluation", "scheduled", "not_yet", "clinician_said_not_needed", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.sex_freq', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["few_times_week", "about_once_week", "few_times_month", "less_often", "varies_a_lot", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.intimacy', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["enjoyable_natural", "scheduled_around_calendar", "feels_like_obligation", "hard_to_relax", "desire_decreased", "pain_discomfort", "want_closeness_not_about_conception", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.support', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["family", "friends", "clinician", "therapist_support_group", "no_one_knows", "very_little_support", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.occupation', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["work", "student", "manage_household", "not_working_studying", "enter_job", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.occupation_detail', 'TEXT', 'ONBOARDING', 'HER_PRIVATE', '{"maxLength": 80}'::jsonb, 1),
    ('onboarding.planning.work_nature', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["mostly_sitting", "on_feet_long", "physically_demanding", "high_emotional_responsibility", "shift_overnight", "traveling_commuting", "can_take_breaks", "hard_to_take_breaks", "every_day_different"]}'::jsonb, 1),
    ('onboarding.planning.sleep', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["enough_sleep", "not_enough", "schedule_changes_a_lot", "shift_overnight", "trouble_falling_asleep", "wake_often", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.lifestyle', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["move_regularly", "mostly_inactive", "smoke_nicotine", "drink_alcohol", "irregular_meals", "dietary_restrictions", "rarely_time_for_myself", "none", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.mental', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["calm", "hopeful", "tired", "anxious", "irritable", "sad", "lonely", "emotions_changed_a_lot", "pregnancy_takes_up_thoughts", "hard_to_tell", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.pressure', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["knowing_what_to_do", "not_missing_fertile_window", "constant_waiting", "fear_it_wont_happen", "age_time_pressure", "comments_from_others", "testing_treatment", "relationship_tension", "none_right_now", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.health_behavior', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["want_details", "short_list_next_steps", "need_help_questions", "read_too_much_anxious", "avoid_info_postpone", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.planning.rest', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["work_school", "walk", "exercise", "music", "reading_movies_shows", "creative_activities", "time_with_people", "time_alone", "travel_nature", "nothing_helps", "something_else"]}'::jsonb, 1),
    ('onboarding.planning.behavior', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"requiredKeys": ["planning", "depth", "length", "reminders", "steps"], "allowedKeys": ["planning", "depth", "length", "reminders", "steps"]}'::jsonb, 1),
    ('onboarding.planning.tone', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["gentle", "friendly", "close_friend", "direct"]}'::jsonb, 1)
ON CONFLICT (field_id) DO NOTHING;
