-- E17-DEFINITIONS-PERIODS: canonical field registrations for the CYCLE period onboarding.
-- Sourced from the final verified legacy state (reference-repos/momna-onboarding-legacy,
-- 20260726101300_required_questions.sql -- schema row version 2).
INSERT INTO momna.canonical_field_definitions(field_id, data_type, domain_owner, sensitivity_class, validation_schema, definition_version)
VALUES
    ('onboarding.cycle.goals', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["know_next_period", "understand_symptoms", "manage_cramps", "understand_mood", "plan_events", "reproductive_health", "fertile_days", "birth_control_info", "sexual_health", "simple_calendar"]}'::jsonb, 1),
    ('onboarding.cycle.lmp', 'DATE', 'ONBOARDING', 'HER_PRIVATE', '{"maxDaysFromNow": 0, "minDaysFromNow": -60}'::jsonb, 1),
    ('onboarding.cycle.regularity', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["around_expected", "timing_changes", "every_cycle_different", "just_starting", "no_periods_bc_or_treatment", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.flow', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["lasts_1_2", "lasts_3_5", "lasts_6_7", "longer_than_week", "light", "moderate", "heavy", "bleed_through_often", "varies_cycle_to_cycle", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.symptoms', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["cramps", "headaches", "mood", "anxiety", "energy", "sleep", "appetite", "skin", "bloating", "breast_tenderness", "focus", "sex_drive", "nothing_noticeable", "not_sure_yet"]}'::jsonb, 1),
    ('onboarding.cycle.impact', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["hardly_at_all", "sometimes_change_plans", "regularly_affects", "cannot_do_normal", "depends_on_month", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.diagnoses', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["pcos", "endometriosis", "fibroids", "adenomyosis", "anemia", "thyroid", "bleeding_condition", "something_else", "no", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.meds', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["birth_control_pills", "hormonal_iud", "copper_iud", "implant_patch_ring_shot", "other_prescription", "iron_vitamins", "none", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.preg_history', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["no", "ended_in_birth", "miscarriage", "chose_to_end", "ended_medical_reasons", "ectopic_or_molar", "more_than_one", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.birth_history', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["vaginal_birth", "planned_c_section", "emergency_c_section", "severe_tear", "heavy_blood_loss", "high_bp_preeclampsia", "surgery_uterus_ovaries", "clinician_noted_other", "none", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.family', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["cancer_close_relative", "early_menopause", "blood_clots", "heart_attack_young", "diabetes", "osteoporosis", "thyroid_disease", "something_else", "no_clinician_mentioned", "dont_know_family_history", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.health_behavior', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["routine_visits", "appointment_when_symptoms", "put_off_appointments", "hard_to_find_trust", "bad_experience_avoid", "not_sure_checkups", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.occupation', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["work", "student", "manage_household", "not_working_studying", "enter_job", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.occupation_detail', 'TEXT', 'ONBOARDING', 'HER_PRIVATE', '{"maxLength": 80}'::jsonb, 1),
    ('onboarding.cycle.work_nature', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["mostly_sitting", "on_feet_long", "physically_demanding", "emotionally_demanding", "shift_overnight", "traveling_commuting", "working_from_home", "can_take_breaks", "hard_to_take_breaks", "every_day_different"]}'::jsonb, 1),
    ('onboarding.cycle.sleep', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["consistent_enough", "consistent_not_enough", "bedtime_varies", "shift_overnight", "trouble_falling_asleep", "wake_often", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.activity', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["exercise_regularly", "walk_no_workouts", "mixed_days", "mostly_inactive", "job_already_demanding", "movement_restrictions", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.mental', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["calm", "energetic", "tired", "overwhelmed", "anxious", "irritable", "sad", "lonely", "mood_changed_a_lot", "hard_to_tell", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.health_barrier', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["not_enough_time", "not_enough_energy", "i_forget", "hard_without_plan", "conflicting_info", "afraid_bad_news", "cost_or_access", "nothing_gets_in_way", "something_else"]}'::jsonb, 1),
    ('onboarding.cycle.rest', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["sleep_quiet", "walk", "exercise", "music", "reading", "creative_activities", "time_with_people", "time_alone", "games_movies_shows", "travel_nature", "not_sure_yet", "something_else"]}'::jsonb, 1),
    ('onboarding.cycle.partner', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["one_steady", "relationship_no_live", "casual_multiple", "no_partner", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.partner_support', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["understands_supports", "tries_not_always", "hard_to_explain", "little_support", "relationship_tense", "pressured_unsafe", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.sex_active', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["yes_regularly", "sometimes", "not_right_now", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.sex_freq', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["few_times_week", "about_once_week", "few_times_month", "less_often", "varies_a_lot", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.sex_comfort', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["comfortable", "want_more", "want_less_pressure", "desire_changes_with_cycle", "desire_decreased", "pain_discomfort", "hard_to_relax", "want_help_talking", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.protection', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["condoms", "hormonal_bc", "iud_implant", "other_method", "sometimes_unprotected", "pregnancy_acceptable", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.cycle.behavior', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"requiredKeys": ["planning", "depth", "length", "reminders", "steps"], "allowedKeys": ["planning", "depth", "length", "reminders", "steps"]}'::jsonb, 1),
    ('onboarding.cycle.tone', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["gentle", "friendly", "close_friend", "direct"]}'::jsonb, 1)
ON CONFLICT (field_id) DO NOTHING;
