-- E17-DEFINITIONS-PERIODS: canonical field registrations for the PREGNANCY period onboarding.
-- Sourced from the final verified legacy state (reference-repos/momna-onboarding-legacy,
-- 20260726101300_required_questions.sql -- schema row version 2). `edd`/`lmp` use the
-- minDaysFromNow/maxDaysFromNow relative bounds (7..294 days ahead for an estimated due date;
-- 14..308 days back for a last-menstrual-period date) instead of fixed calendar dates.
INSERT INTO momna.canonical_field_definitions(field_id, data_type, domain_owner, sensitivity_class, validation_schema, definition_version)
VALUES
    ('onboarding.pregnancy.dates_method', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["gestational_age", "edd", "unknown"]}'::jsonb, 1),
    ('onboarding.pregnancy.gestational_weeks', 'NUMBER', 'ONBOARDING', 'HER_PRIVATE', '{"minimum": 1, "maximum": 45}'::jsonb, 1),
    ('onboarding.pregnancy.edd', 'DATE', 'ONBOARDING', 'HER_PRIVATE', '{"minDaysFromNow": 7, "maxDaysFromNow": 294}'::jsonb, 1),
    ('onboarding.pregnancy.lmp', 'DATE', 'ONBOARDING', 'HER_PRIVATE', '{"maxDaysFromNow": -14, "minDaysFromNow": -308}'::jsonb, 1),
    ('onboarding.pregnancy.multiples', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["one_baby", "twins", "triplets", "more_than_three", "unknown", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.goals', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["understand_development", "understand_body_changes", "manage_symptoms", "prepare_appointments", "eat_manageable", "stay_active_safely", "feel_less_anxious", "prepare_labor", "prepare_life_after_birth", "support_partner_relationship"]}'::jsonb, 1),
    ('onboarding.pregnancy.care', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["regular_appointments", "first_scheduled", "choosing_provider", "not_started_yet", "also_maternal_fetal_specialist", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.special_care', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["routine_so_far", "need_frequent_monitoring", "exercise_limits", "work_travel_limits", "food_medication_instructions", "advised_rest", "not_discussed_yet", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.symptoms', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["nausea", "fatigue", "sleepiness", "trouble_sleeping", "back_pelvic_pain", "heartburn", "constipation_bloating", "headaches", "swelling", "shortness_of_breath", "anxiety", "mood_changes", "nothing_much", "something_else"]}'::jsonb, 1),
    ('onboarding.pregnancy.preg_history', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["first_pregnancy", "ended_in_birth", "miscarriage", "chose_to_end", "ended_medical_reasons", "ectopic_or_molar", "more_than_one", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.prev_details', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["c_section", "preterm_birth", "high_bp_preeclampsia", "gestational_diabetes", "heavy_blood_loss", "repeated_loss", "surgery_uterus", "something_else", "no", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.current_context', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["blood_pressure", "blood_sugar", "anemia_iron", "thyroid", "preterm_labor_risk", "placenta_bleeding", "baby_growth", "something_else", "no", "dont_know_yet", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.meds', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["prenatal_vitamin", "folic_acid", "iron", "vitamin_d", "clinician_prescribed", "other_supplements", "nothing_right_now", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.family_context', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["testing_complete", "testing_scheduled", "next_step_undecided", "no", "not_discussed_yet", "not_sure", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.family_details', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["condition_in_several_relatives", "congenital_condition", "developmental_condition", "repeated_loss_or_stillbirth", "genetic_counseling_appointment", "something_else", "dont_know_exact_name", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.occupation', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["work", "student", "manage_household", "on_leave_not_working", "enter_job", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.occupation_detail', 'TEXT', 'ONBOARDING', 'HER_PRIVATE', '{"maxLength": 80}'::jsonb, 1),
    ('onboarding.pregnancy.work_nature', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["mostly_sitting", "on_feet_long", "physical_lifting", "high_emotional_responsibility", "shift_overnight", "traveling_commuting", "can_take_breaks", "hard_to_take_breaks", "every_day_different"]}'::jsonb, 1),
    ('onboarding.pregnancy.activity', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["continuing_with_approval", "light_activity_walks", "moving_less_symptoms", "already_demanding", "clinician_limited", "not_sure_whats_safe", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.sleep', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["mostly_okay", "not_enough", "trouble_falling_asleep", "wake_often", "symptoms_interrupt", "shift_overnight", "every_day_different", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.eating', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["about_the_same", "nausea_limits", "appetite_changed", "cant_eat_regular_times", "specific_dietary_instructions", "allergies_restrictions", "worry_eating_right", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.mental', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["calm", "happy", "tired", "overwhelmed", "anxious", "irritable", "sad", "disconnected", "hard_to_feel_happy_about_pregnancy", "emotions_change_often", "hard_to_tell", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.fears', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["babys_health", "my_own_health", "symptoms_body_changes", "test_results", "labor_delivery", "pregnancy_loss", "money_or_work", "my_relationship", "life_after_baby_arrives", "none_right_now", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.support_network', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["partner", "family", "friends", "clinician", "therapist_support_group", "very_little_help", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.rest', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"allowedKeys": ["work_school", "walk", "exercise_movement", "music", "reading_movies_shows", "creative_activities", "time_with_people", "time_alone", "travel_nature", "not_sure_yet", "something_else"]}'::jsonb, 1),
    ('onboarding.pregnancy.partner', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["yes_live_together", "yes_no_live_together", "casual_multiple", "no_partner", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.partner_support', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["understands_supports", "tries_not_always", "emotionally_supportive_but_responsibilities_fall_on_me", "hard_to_ask_for_help", "little_support", "relationship_tense", "pressured_unsafe", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.sex_active', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["yes_regularly", "sometimes", "not_right_now", "care_team_advised_avoid", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.sex_freq', 'ENUM', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedValues": ["few_times_week", "about_once_week", "few_times_month", "less_often", "varies_a_lot", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.intimacy', 'OBJECT', 'ONBOARDING', 'MEDICAL_PRIVATE', '{"allowedKeys": ["nothing_changed", "desire_increased", "desire_decreased", "pain_discomfort", "worry_harm_pregnancy", "partner_worries_harm", "want_affection_without_sex", "care_team_restrictions", "want_help_talking", "prefer_not_to_say"]}'::jsonb, 1),
    ('onboarding.pregnancy.behavior', 'OBJECT', 'ONBOARDING', 'HER_PRIVATE', '{"requiredKeys": ["planning", "depth", "length", "reminders", "steps"], "allowedKeys": ["planning", "depth", "length", "reminders", "steps"]}'::jsonb, 1),
    ('onboarding.pregnancy.tone', 'ENUM', 'ONBOARDING', 'HER_PRIVATE', '{"allowedValues": ["gentle", "friendly", "close_friend", "direct"]}'::jsonb, 1)
ON CONFLICT (field_id) DO NOTHING;
