package com.momna.platform.ai;

public enum AiErrorCode {
    PURPOSE_MISMATCH, CONTEXT_NOT_FOUND, CONTEXT_VERSION_MISMATCH, PRIVACY_OR_SAFETY_DENIED,
    PROMPT_NOT_FOUND, PROMPT_VERSION_NOT_FOUND, MODEL_POLICY_NOT_FOUND, MODEL_POLICY_VERSION_NOT_FOUND,
    INVALID_PROMPT_VARIABLES, OUTPUT_VALIDATOR_NOT_FOUND, OUTPUT_VALIDATION_FAILED, PROVIDER_UNAVAILABLE,
    PROVIDER_TIMEOUT, RATE_LIMITED, FALLBACK_EXHAUSTED, BUDGET_EXCEEDED, COST_POLICY_UNKNOWN,
    CACHE_FAILURE, VALIDATION_ERROR
}
