package com.momna.core.privacy;

public enum PolicyDecisionCode {
    ALLOW,
    UNAUTHENTICATED,
    VALIDATION_ERROR,
    POLICY_VERSION_MISMATCH,
    OWNER_REQUIRED,
    PARTNER_PRIVATE_DENIED,
    RELATIONSHIP_REQUIRED,
    RELATIONSHIP_INACTIVE,
    CONSENT_REQUIRED,
    CONSENT_WITHDRAWN,
    CONSENT_VERSION_MISMATCH,
    RAW_SENSITIVE_CROSS_BOUNDARY_DENIED,
    SCOPE_NOT_ALLOWED
}
